steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/code-quality-repo/code-quality-dashboard:$BUILD_ID', '.']

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/code-quality-repo/code-quality-dashboard:$BUILD_ID']

# 3. Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'code-quality-dashboard' # This will be the name of your Cloud Run service
    - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/code-quality-repo/code-quality-dashboard:$BUILD_ID'
    - '--region=us-central1' # You can change this to your preferred region
    - '--platform=managed'
    - '--allow-unauthenticated' # This makes the service publicly accessible
    - '--set-env-vars=BIGQUERY_TABLE_ID=joeshireylearn-374523.existing_samples.v_all_samples,PROJECT_ID=joeshireylearn-374523'
#    - '--set-env-vars=BIGQUERY_TABLE_ID=panoply-ai-dev.samples_views.all_samples_view,PROJECT_ID=panoply-ai-dev'

# Store the image name for later builds
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/code-quality-repo/code-quality-dashboard:$BUILD_ID'